### ISSUE TITLE
Is it possible to have a different dev path and distribution path?

### ISSUE THREAD

**Issue by kittykatattack** [moarwick/elm-webpack-starter#11]
Hi!

This is just a general question about webpack configuration.. hope it's OK to ask here?
My local path for images is on my dev server is:

```
"../images"
```

But, when the project is deployed it will need to grab the images from here:

```
"/digitalresources/html/eng4cc/images/"
```

Is it possible to configure webpack to use this path when it builds to the `dist` folder?

**Comment by moarwick** [comment]
It should be possible by specifying a `publicPath` in your `output` block:

```
output: {
  path:       path.resolve( __dirname, 'dist/' ),
  filename:   '[hash].js',
  publicPath: 'dist/some/other/folder/'
},
```

Then, modify the destination of the `cp` command in your `build` script, in `package.json`:

```
cp -r src/img/ dist/some/other/folder/
```

Hope it helps!
