### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kittykatattack** [moarwick/elm-webpack-starter#15]
Hi, just a "Thank you!" for bumping this up to 0.17 😄 
I user elm-webpack-starter with all my Elm projects and love it.

**Comment by moarwick** [comment]
Appreciate it. Glad it's useful!

**Comment by joakin** [comment]
I want to echo back the thanks. This boilerplate is very useful.

**Comment by decentral1se** [comment]
Yeah, don't want to spam but it's awesome. Thanks!
