### ISSUE TITLE
Uncaught ReferenceError: _elm_lang$core$Json_Decode_ops is not defined

### ISSUE THREAD

**Issue by kaaloo** [moarwick/elm-webpack-starter#25]
Running `npm start` will raise this error when using elm-lang/core 4.0.5.  Works fine with elm-lang/core 4.0.4.

![selection_001](https://cloud.githubusercontent.com/assets/67010/17584315/1cf98fa2-5fb6-11e6-994b-59067998ff12.jpg)

**Comment by moarwick** [comment]
Not seeing it, so i'm presuming it's in your Elm code? Looks like it's checkbox (form fields) related perhaps? Try compiling it direct, to see if it's related to elm-webpack-starter

**Comment by kaaloo** [comment]
Weird, I just cloned elm-webpack-starter, no code of mine here.  I'll try again in a bit and let you know.

**Comment by kaaloo** [comment]
You're right!  Sorry for the noise.
