### ISSUE TITLE
Not reloading when modifying Components.Hello

### ISSUE THREAD

**Issue by jscriptcoder** [moarwick/elm-webpack-starter#27]
Hi there,

I'm just toying around with this kit starter, by the way, great job... but I noticed that when I modify the component Hello.elm, the app doesn't reload. It does so when I modify Main.elm though. I followed the installation, and I get the app running, but it doesn't seem to reload with changes in subfolders. Could it be an issue in elm-hot-loader?

Thanks

**Comment by rtfeldman** [comment]
@moarwick May be related to https://github.com/rtfeldman/node-elm-compiler/pull/36 - which is now fixed. 😄

**Comment by moarwick** [comment]
@rtfeldman Thanks! Btw, any interest in "taking over" this repo? I feel super unqualified continuing on since I don't actually write any Elm.. I was hoping to allocate some time to learning it but it's been a ~year now :(

**Comment by benansell** [comment]
Hi @moarwick - If it's helpful I would be happy to either maintain this repo or help you maintain it?  Recently I started a similar one aimed at using elm-css instead of sass - [elm-webpack-seed](https://github.com/benansell/elm-webpack-seed)

**Comment by moarwick** [comment]
Just pushed an update, and verified hot-reloading to be working. Some other changes went in a well -- see README. 

@benansell: Cool. Do you know both Webpack and Elm pretty well, keeping up? I'm happy to get PRs for improvements then we can talk hand-over; not sure what the best way would be..

**Comment by benansell** [comment]
Mostly I just muddle my way through ;) - I have added a watch to the repo and will have a look at any issues that come in to see if I can help or feel free to add a mention to me on any you want me to pick up.

**Comment by jscriptcoder** [comment]
Just wanted to thank you guys for taking care of this issue :-)

**Comment by bzums** [comment]
Hey, I still have the problem, can somebody confirm that? @moarwick maybe?
