### ISSUE TITLE
feature request: create project from command line

### ISSUE THREAD

**Issue by larfadin** [moarwick/elm-webpack-starter#29]
Hi,

It would be great if it were possible to maybe install globally elm webpack starter and then to create project like `elm-webpack-starter create MyProject`.

BTW thanks for your work, it help me a lot, webpack is so fuck up and so hard to understand, and everything that can help use it without understanding the shit about it is very welcome.

**Comment by moarwick** [comment]
yeah, would be nice -- we use such React/Redux project generator at work https://github.com/TrueCar/gluestick -- but unlikely i'll have the time :( 

keep in mind that you can  clone `elm-webpack-starter` directly to a new project folder. you still need to nuke `.git` and re-init your own repo after that, but at least you've pulled the latest ver:

```
git clone https://github.com/moarwick/elm-webpack-starter my-project
cd my-project
rm -rf .git
git init
```

And edit your meta in `package.json`...
