### ISSUE TITLE
Webpack Server not reloading

### ISSUE THREAD

**Issue by sircharleswatson** [moarwick/elm-webpack-starter#3]
Hi, I'm not sure what's wrong but if Elm runs into an error and it can't compile, it seems that webpack stops picking up changes after that. This happens with the elm-webpack-starter webpack.config and any other ones I try with elm + webpack. Any thoughts?

**Comment by moarwick** [comment]
Hmm, I wonder if we need something like the 'NoErrorsPlugin' (https://github.com/webpack/docs/wiki/list-of-plugins). Will try to have a look soon..

**Comment by sircharleswatson** [comment]
@pmdesgn I think it's something to do with the actual loader. but ya, that might be a good addition. I'm talking to the guys over here: https://github.com/rtfeldman/elm-webpack-loader/issues/30

feel free to add your input.

**Comment by moarwick** [comment]
Hmm, I just tried it again briefly and my process seems to recover fine when errors are introduced/resolved as I work. Sadly, I haven't had a chance to work with Elm more but please update this issue (or submit a PR) if there are any developments on this.. happy to improve this repo. Thx!
