### ISSUE TITLE
JS Error: Reload not working

### ISSUE THREAD

**Issue by 7underlines** [moarwick/elm-webpack-starter#31]
I installed everything.

I tried to change
, span[][ text "FTW!" ]
into
, span[][ text "FTW!!" ]

Then this happens:

![screenshot from 2016-11-09 12-54-53](https://cloud.githubusercontent.com/assets/17121556/20137619/d6a720de-a67b-11e6-8db4-196d6cbc8bb0.png)

What I'm doing wrong?
I'm on Fedora 24 and use Atom as Editor.

**Comment by moarwick** [comment]
Sorry, I'm not sure. Not seeing this behavior on OSX, changing `Main.js` hot-reloads fine.  Are you also running `elm-test` perhaps?  See this issue: https://github.com/rtfeldman/node-test-runner/issues/62

**Comment by 7underlines** [comment]
I found the issue. It was caused by an old elm-hot-loader version.

I changed the file package.json
"elm-hot-loader": "^0.3.2", 
to
"elm-hot-loader": "^0.4.1",

Then
npm install
npm start

And now it's working fine :dancer: 

Thanks for your help.
