### ISSUE TITLE
issue on windows with rimraf?

### ISSUE THREAD

**Issue by zeukterialpneumaion** [moarwick/elm-webpack-starter#38]
i am getting an issue with rimraf not being recognised on windows....
apologies if this is an error on my side::
::
C:\Users\aj\Documents\programminglanguages\elm\my-elm-project [master]> npm run reinstall

> elm-webpack-starter@0.8.0 reinstall C:\Users\aj\Documents\programminglanguages\elm\my-elm-project
> rimraf node_modules && npm uninstall -g elm && npm i -g elm && npm i && elm package install

'rimraf' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aj\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-c
li.js" "run" "reinstall"
npm ERR! node v4.1.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! elm-webpack-starter@0.8.0 reinstall: `rimraf node_modules && npm uninstall -g elm && npm i -g elm && npm i && e
lm package install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm-webpack-starter@0.8.0 reinstall script 'rimraf node_modules && npm uninstall -g elm && npm i
-g elm && npm i && elm package install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the elm-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf node_modules && npm uninstall -g elm && npm i -g elm && npm i && elm package install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs elm-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls elm-webpack-starter
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\aj\Documents\programminglanguages\elm\my-elm-project\npm-debug.log

**Comment by moarwick** [comment]
hmm,looks my bad, if you're doing a fresh clone, it won't have `rimraf` installed (duh!) need to update the repo, in the meantime, try installing `rimraf` globally first, then run the `reinstall` script..

`npm i rimraf`
`npm run reinstall`

**Comment by moarwick** [comment]
Updated the repo now..

**Comment by zeukterialpneumaion** [comment]
hi ! thankyou for updating!! So, updated tried once more....hmmm... still getting errors unfortunately... sure its on my sid now could you help?
...
elm-webpack-starter@0.8.1 C:\Users\aj\Documents\programminglanguages\elm\my-elm-project
`-- rimraf@2.5.4
  `-- glob@7.1.1
    +-- fs.realpath@1.0.0
    +-- inflight@1.0.6
    | `-- wrappy@1.0.2
    +-- inherits@2.0.3
    +-- minimatch@3.0.3
    | `-- brace-expansion@1.1.6
    |   +-- balanced-match@0.4.2
    |   `-- concat-map@0.0.1
    +-- once@1.4.0
    `-- path-is-absolute@1.0.1

The system cannot find the path specified.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aj\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "reinstall"
npm ERR! node v4.1.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! elm-webpack-starter@0.8.1 reinstall: `npm i rimraf && rimraf node_modules && npm uninstall -g elm && npm i -g elm && npm i && elm package install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm-webpack-starter@0.8.1 reinstall script 'npm i rimraf && rimraf node_modules && npm uninstall -g elm && npm i -g elm && npm i && elm package install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the elm-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i rimraf && rimraf node_modules && npm uninstall -g elm && npm i -g elm && npm i && elm package install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs elm-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls elm-webpack-starter
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
[npm-debug.txt](https://github.com/moarwick/elm-webpack-starter/files/637013/npm-debug.txt)

**Comment by moarwick** [comment]
Hmm, not a Windows user, so I'm just guessing here. I would try:

1) Install `rimraf` globally `npm i rimraf -g`, then try again..
2) If that fails, you don't really need rimraf. if you freshly cloned it, you can just do the install commands individually: `npm i -g elm`, `elm package install`, and `npm i`.

Note: `rimraf` is a Node package which is supposed to provide a normalized command for deleting a directory. I believe on Windows, the same can be accomplished via the `rmdir` command..

**Comment by zeukterialpneumaion** [comment]
Aha! YES! Success....

Thankyou Peter!

Ok! I have it!

So yes, its the rmdir packages that were causing all issues,

(will deal with that later...!

yes, its a reluctant windows user set of problems ....)

but great! ELM!!! am so glad for this starter project .. can dive into
the elm paradigm now! Awesome,

many , many thanks. jez.

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

terminal readout::

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

C:\Users\aj\Documents\programminglanguages\elm\my-elm-project [master +2
~0 -0 !]> npm i -g elm
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
C:\Users\aj\AppData\Roaming\npm\elm ->
C:\Users\aj\AppData\Roaming\npm\node_modules\elm\binwrappers\elm
C:\Users\aj\AppData\Roaming\npm\elm-make ->
C:\Users\aj\AppData\Roaming\npm\node_modules\elm\binwrappers\elm-make
C:\Users\aj\AppData\Roaming\npm\elm-package ->
C:\Users\aj\AppData\Roaming\npm\node_modules\elm\binwrappers\elm-package
C:\Users\aj\AppData\Roaming\npm\elm-repl ->
C:\Users\aj\AppData\Roaming\npm\node_modules\elm\binwrappers\elm-repl
C:\Users\aj\AppData\Roaming\npm\elm-reactor ->
C:\Users\aj\AppData\Roaming\npm\node_modules\elm\binwrappers\elm-reactor

> elm@0.18.0 install C:\Users\aj\AppData\Roaming\npm\node_modules\elm
> node install.js

Downloading Elm binaries from
https://dl.bintray.com/elmlang/elm-platform/0.18.0/win32-x64.tar.gz
C:\Users\aj\AppData\Roaming\npm
`-- elm@0.18.0

C:\Users\aj\Documents\programminglanguages\elm\my-elm-project [master +1
~0 -0 !]> elm package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 5.0.0
    elm-lang/html 2.0.0
    elm-lang/http 1.0.0
    elm-lang/virtual-dom 2.0.2
    evancz/elm-markdown 3.0.1

Do you approve of this plan? [Y/n] y
Starting downloads...

  ÔùÅ elm-lang/http 1.0.0
  ÔùÅ elm-lang/html 2.0.0
  ÔùÅ elm-lang/virtual-dom 2.0.2
  ÔùÅ evancz/elm-markdown 3.0.1

ÔùÅ elm-lang/core 5.0.0
Packages configured successfully!
C:\Users\aj\Documents\programminglanguages\elm\my-elm-project [master +2
~0 -0 !]> npm i
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> elm@0.18.0 install
C:\Users\aj\Documents\programminglanguages\elm\my-elm-project\node_modules\elm
> node install.js

Downloading Elm binaries from
https://dl.bintray.com/elmlang/elm-platform/0.18.0/win32-x64.tar.gz

> node-sass@3.13.0 install
C:\Users\aj\Documents\programminglanguages\elm\my-elm-project\node_modules\node-sass
> node scripts/install.js

Downloading binary from
https://github.com/sass/node-sass/releases/download/v3.13.0/win32-x64-46_binding.node
Download complete  ] - :
Binary saved to
C:\Users\aj\Documents\programminglanguages\elm\my-elm-project\node_modules\node-sass\vendor\win32-x64-46
\binding.node
Caching binary to
C:\Users\aj\AppData\Roaming\npm-cache\node-sass\3.13.0\win32-x64-46_binding.node

> node-sass@3.13.0 postinstall
C:\Users\aj\Documents\programminglanguages\elm\my-elm-project\node_modules\node-sass
> node scripts/build.js

Binary found at
C:\Users\aj\Documents\programminglanguages\elm\my-elm-project\node_modules\node-sass\vendor\win32-x64-46
\binding.node
Testing binary
Binary is fine
elm-webpack-starter@0.8.1
C:\Users\aj\Documents\programminglanguages\elm\my-elm-project
+-- autoprefixer@6.5.3
| +-- browserslist@1.4.0
| +-- caniuse-db@1.0.30000592
| +-- normalize-range@0.1.2
| +-- num2fraction@1.2.2
| +-- postcss@5.2.6
| | +-- js-base64@2.1.9
| | `-- source-map@0.5.6
| `-- postcss-value-parser@3.3.0
+-- bootstrap-sass@3.3.7
+-- copy-webpack-plugin@4.0.1
| +-- bluebird@2.11.0
| +-- fs-extra@0.26.7
| | +-- graceful-fs@4.1.11
| | +-- jsonfile@2.4.0
| | +-- klaw@1.3.1
| | `-- path-is-absolute@1.0.1
| +-- glob@6.0.4
| | +-- inflight@1.0.6
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.3
| | `-- once@1.4.0
| +-- is-glob@3.1.0
| | `-- is-extglob@2.1.0
| +-- loader-utils@0.2.16
| | +-- big.js@3.1.3
| | +-- emojis-list@2.1.0
| | `-- json5@0.5.1
| +-- lodash@4.17.2
| +-- minimatch@3.0.3
| | `-- brace-expansion@1.1.6
| |   +-- balanced-match@0.4.2
| |   `-- concat-map@0.0.1
| `-- node-dir@0.1.16
+-- css-loader@0.25.0
| +-- babel-code-frame@6.16.0
| | +-- esutils@2.0.2
| | `-- js-tokens@2.0.0
| +-- css-selector-tokenizer@0.6.0
| | +-- cssesc@0.1.0
| | +-- fastparse@1.1.1
| | `-- regexpu-core@1.0.0
| |   +-- regenerate@1.3.2
| |   +-- regjsgen@0.2.0
| |   `-- regjsparser@0.1.5
| |     `-- jsesc@0.5.0
| +-- cssnano@3.8.1
| | +-- decamelize@1.2.0
| | +-- defined@1.0.0
| | +-- has@1.0.1
| | | `-- function-bind@1.1.0
| | +-- postcss-calc@5.3.1
| | | +-- postcss-message-helpers@2.0.0
| | | `-- reduce-css-calc@1.3.0
| | |   +-- math-expression-evaluator@1.2.14
| | |   | `-- lodash.indexof@4.0.5
| | |   `-- reduce-function-call@1.0.2
| | +-- postcss-colormin@2.2.1
| | | `-- colormin@1.1.2
| | |   +-- color@0.11.4
| | |   | +-- color-convert@1.8.2
| | |   | | `-- color-name@1.1.1
| | |   | `-- color-string@0.3.0
| | |   `-- css-color-names@0.0.4
| | +-- postcss-convert-values@2.5.0
| | +-- postcss-discard-comments@2.0.4
| | +-- postcss-discard-duplicates@2.0.2
| | +-- postcss-discard-empty@2.1.0
| | +-- postcss-discard-overridden@0.1.1
| | +-- postcss-discard-unused@2.2.3
| | | `-- uniqs@2.0.0
| | +-- postcss-filter-plugins@2.0.2
| | | `-- uniqid@4.1.0
| | |   `-- macaddress@0.2.8
| | +-- postcss-merge-idents@2.1.7
| | +-- postcss-merge-longhand@2.0.1
| | +-- postcss-merge-rules@2.0.10
| | | `-- vendors@1.0.1
| | +-- postcss-minify-font-values@1.0.5
| | +-- postcss-minify-gradients@1.0.5
| | +-- postcss-minify-params@1.0.5
| | | `-- alphanum-sort@1.0.2
| | +-- postcss-minify-selectors@2.0.7
| | | `-- postcss-selector-parser@2.2.2
| | |   +-- flatten@1.0.2
| | |   +-- indexes-of@1.0.1
| | |   `-- uniq@1.0.1
| | +-- postcss-normalize-charset@1.1.1
| | +-- postcss-normalize-url@3.0.7
| | | +-- is-absolute-url@2.0.0
| | | `-- normalize-url@1.8.0
| | |   +-- prepend-http@1.0.4
| | |   +-- query-string@4.2.3
| | |   | `-- strict-uri-encode@1.1.0
| | |   `-- sort-keys@1.1.2
| | |     `-- is-plain-obj@1.1.0
| | +-- postcss-ordered-values@2.2.2
| | +-- postcss-reduce-idents@2.3.1
| | +-- postcss-reduce-initial@1.0.0
| | +-- postcss-reduce-transforms@1.0.4
| | +-- postcss-svgo@2.1.5
| | | +-- is-svg@2.1.0
| | | | `-- html-comment-regex@1.1.1
| | | `-- svgo@0.7.1
| | |   +-- coa@1.0.1
| | |   | `-- q@1.4.1
| | |   +-- colors@1.1.2
| | |   +-- csso@2.2.1
| | |   | `-- clap@1.1.2
| | |   +-- sax@1.2.1
| | |   `-- whet.extend@0.9.9
| | +-- postcss-unique-selectors@2.0.2
| | `-- postcss-zindex@2.2.0
| +-- lodash.camelcase@3.0.1
| | `-- lodash._createcompounder@3.0.0
| |   +-- lodash.deburr@3.2.0
| |   | `-- lodash._root@3.0.1
| |   `-- lodash.words@3.2.0
| +-- object-assign@4.1.0
| +-- postcss-modules-extract-imports@1.0.1
| +-- postcss-modules-local-by-default@1.1.1
| +-- postcss-modules-scope@1.0.2
| +-- postcss-modules-values@1.2.2
| | `-- icss-replace-symbols@1.0.2
| `-- source-list-map@0.1.7
+-- elm@0.18.0
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- promise@7.1.1
| | `-- asap@2.0.5
| +-- request@2.74.0
| | +-- aws-sign2@0.6.0
| | +-- aws4@1.5.0
| | +-- bl@1.1.2
| | +-- caseless@0.11.0
| | +-- combined-stream@1.0.5
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.0
| | +-- forever-agent@0.6.1
| | +-- form-data@1.0.1
| | +-- har-validator@2.0.6
| | | +-- is-my-json-valid@2.15.0
| | | | +-- generate-function@2.0.0
| | | | +-- generate-object-property@1.2.0
| | | | | `-- is-property@1.0.2
| | | | `-- jsonpointer@4.0.0
| | | `-- pinkie-promise@2.0.1
| | |   `-- pinkie@2.0.4
| | +-- hawk@3.1.3
| | | +-- boom@2.10.1
| | | +-- cryptiles@2.0.5
| | | +-- hoek@2.16.3
| | | `-- sntp@1.0.9
| | +-- http-signature@1.1.1
| | | +-- assert-plus@0.2.0
| | | +-- jsprim@1.3.1
| | | | +-- extsprintf@1.0.2
| | | | +-- json-schema@0.2.3
| | | | `-- verror@1.3.6
| | | `-- sshpk@1.10.1
| | |   +-- asn1@0.2.3
| | |   +-- assert-plus@1.0.0
| | |   +-- bcrypt-pbkdf@1.0.0
| | |   +-- dashdash@1.14.1
| | |   | `-- assert-plus@1.0.0
| | |   +-- ecc-jsbn@0.1.1
| | |   +-- getpass@0.1.6
| | |   | `-- assert-plus@1.0.0
| | |   +-- jodid25519@1.0.2
| | |   +-- jsbn@0.1.0
| | |   `-- tweetnacl@0.14.4
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- mime-types@2.1.13
| | | `-- mime-db@1.25.0
| | +-- node-uuid@1.4.7
| | +-- oauth-sign@0.8.2
| | +-- qs@6.2.1
| | +-- stringstream@0.0.5
| | +-- tough-cookie@2.3.2
| | `-- tunnel-agent@0.4.3
| `-- tar@2.2.1
|   +-- block-stream@0.0.9
|   `-- fstream@1.0.10
+-- elm-hot-loader@0.5.3
+-- elm-webpack-loader@3.1.0
| `-- node-elm-compiler@4.2.0
|   +-- cross-spawn@4.0.0
|   +-- firstline@1.2.0
|   +-- lodash@4.14.2
|   `-- temp@0.8.3
|     +-- os-tmpdir@1.0.2
|     `-- rimraf@2.2.8
+-- extract-text-webpack-plugin@1.0.1
| +-- async@1.5.2
| `-- webpack-sources@0.1.3
+-- file-loader@0.9.0
+-- html-webpack-plugin@2.24.1
| +-- bluebird@3.4.6
| +-- html-minifier@3.2.3
| | +-- camel-case@3.0.0
| | | +-- no-case@2.3.0
| | | | `-- lower-case@1.1.3
| | | `-- upper-case@1.1.3
| | +-- clean-css@3.4.21
| | | +-- commander@2.8.1
| | | `-- source-map@0.4.4
| | +-- commander@2.9.0
| | | `-- graceful-readlink@1.0.1
| | +-- he@1.1.0
| | +-- ncname@1.0.0
| | | `-- xml-char-classes@1.0.0
| | +-- param-case@2.1.0
| | `-- relateurl@0.2.7
| +-- pretty-error@2.0.2
| | +-- renderkid@2.0.0
| | | +-- css-select@1.2.0
| | | | +-- boolbase@1.0.0
| | | | +-- css-what@2.1.0
| | | | +-- domutils@1.5.1
| | | | | `-- dom-serializer@0.1.0
| | | | |   +-- domelementtype@1.1.3
| | | | |   `-- entities@1.1.1
| | | | `-- nth-check@1.0.1
| | | +-- dom-converter@0.1.4
| | | | `-- utila@0.3.3
| | | +-- htmlparser2@3.3.0
| | | | +-- domelementtype@1.3.0
| | | | +-- domhandler@2.1.0
| | | | +-- domutils@1.1.6
| | | | `-- readable-stream@1.0.34
| | | |   `-- isarray@0.0.1
| | | `-- utila@0.3.3
| | `-- utila@0.4.0
| `-- toposort@1.0.0
+-- jquery@3.1.1
+-- node-sass@3.13.0
| +-- async-foreach@0.1.3
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | `-- supports-color@2.0.0
| +-- cross-spawn@3.0.1
| | `-- lru-cache@4.0.2
| |   +-- pseudomap@1.0.2
| |   `-- yallist@2.0.0
| +-- gaze@1.1.2
| | `-- globule@1.1.0
| |   +-- glob@7.1.1
| |   `-- lodash@4.16.6
| +-- get-stdin@4.0.1
| +-- glob@7.1.1
| | `-- fs.realpath@1.0.0
| +-- in-publish@2.0.0
| +-- lodash.assign@4.2.0
| +-- lodash.clonedeep@4.5.0
| +-- meow@3.7.0
| | +-- camelcase-keys@2.1.0
| | | `-- camelcase@2.1.1
| | +-- loud-rejection@1.6.0
| | | +-- currently-unhandled@0.4.1
| | | | `-- array-find-index@1.0.2
| | | `-- signal-exit@3.0.2
| | +-- map-obj@1.0.1
| | +-- minimist@1.2.0
| | +-- normalize-package-data@2.3.5
| | | +-- hosted-git-info@2.1.5
| | | +-- is-builtin-module@1.0.0
| | | | `-- builtin-modules@1.1.1
| | | `-- validate-npm-package-license@3.0.1
| | |   +-- spdx-correct@1.0.2
| | |   | `-- spdx-license-ids@1.2.2
| | |   `-- spdx-expression-parse@1.0.4
| | +-- read-pkg-up@1.0.1
| | | +-- find-up@1.1.2
| | | | `-- path-exists@2.1.0
| | | `-- read-pkg@1.1.0
| | |   +-- load-json-file@1.1.0
| | |   | +-- pify@2.3.0
| | |   | `-- strip-bom@2.0.0
| | |   |   `-- is-utf8@0.2.1
| | |   `-- path-type@1.1.0
| | +-- redent@1.0.0
| | | +-- indent-string@2.1.0
| | | | `-- repeating@2.0.1
| | | |   `-- is-finite@1.0.2
| | | `-- strip-indent@1.0.1
| | `-- trim-newlines@1.0.0
| +-- nan@2.4.0
| +-- node-gyp@3.4.0
| | +-- glob@7.1.1
| | +-- nopt@3.0.6
| | | `-- abbrev@1.0.9
| | +-- npmlog@3.1.2
| | | `-- gauge@2.6.0
| | |   `-- has-color@0.1.7
| | +-- osenv@0.1.3
| | | `-- os-homedir@1.0.2
| | +-- path-array@1.0.1
| | | `-- array-index@1.0.0
| | |   `-- es6-symbol@3.1.0
| | |     +-- d@0.1.1
| | |     `-- es5-ext@0.10.12
| | |       `-- es6-iterator@2.0.0
| | +-- semver@5.3.0
| | `-- which@1.2.12
| |   `-- isexe@1.1.2
| +-- npmlog@4.0.1
| | +-- are-we-there-yet@1.1.2
| | | `-- delegates@1.0.0
| | +-- console-control-strings@1.1.0
| | +-- gauge@2.7.2
| | | +-- aproba@1.0.4
| | | +-- has-unicode@2.0.1
| | | +-- string-width@1.0.2
| | | | +-- code-point-at@1.1.0
| | | | `-- is-fullwidth-code-point@1.0.0
| | | |   `-- number-is-nan@1.0.1
| | | +-- supports-color@0.2.0
| | | `-- wide-align@1.1.0
| | `-- set-blocking@2.0.0
| `-- sass-graph@2.1.2
|   +-- glob@7.1.1
|   `-- yargs@4.8.1
|     +-- cliui@3.2.0
|     | `-- wrap-ansi@2.1.0
|     +-- get-caller-file@1.0.2
|     +-- os-locale@1.4.0
|     | `-- lcid@1.0.0
|     |   `-- invert-kv@1.0.0
|     +-- require-directory@2.1.1
|     +-- require-main-filename@1.0.1
|     +-- which-module@1.0.0
|     +-- window-size@0.2.0
|     +-- y18n@3.2.1
|     `-- yargs-parser@2.4.1
|       `-- camelcase@3.0.0
+-- postcss-loader@1.2.0
| `-- postcss-load-config@1.0.0
|   +-- cosmiconfig@2.1.1
|   | +-- js-yaml@3.6.1
|   | | +-- argparse@1.0.9
|   | | | `-- sprintf-js@1.0.3
|   | | `-- esprima@2.7.3
|   | +-- minimist@1.2.0
|   | +-- parse-json@2.2.0
|   | | `-- error-ex@1.3.0
|   | |   `-- is-arrayish@0.2.1
|   | `-- require-from-string@1.2.1
|   +-- postcss-load-options@1.0.2
|   `-- postcss-load-plugins@2.1.0
+-- rimraf@2.5.4
| `-- glob@7.1.1
+-- sass-loader@4.0.2
| `-- async@2.1.4
+-- style-loader@0.13.1
+-- url-loader@0.5.7
| `-- mime@1.2.11
+-- webpack@1.14.0
| +-- acorn@3.3.0
| +-- async@1.5.2
| +-- clone@1.0.2
| +-- enhanced-resolve@0.9.1
| | `-- memory-fs@0.2.0
| +-- interpret@0.6.6
| +-- memory-fs@0.3.0
| | +-- errno@0.1.4
| | | `-- prr@0.0.0
| | `-- readable-stream@2.0.6
| |   +-- core-util-is@1.0.2
| |   +-- isarray@1.0.0
| |   +-- process-nextick-args@1.0.7
| |   `-- util-deprecate@1.0.2
| +-- node-libs-browser@0.7.0
| | +-- assert@1.4.1
| | +-- browserify-zlib@0.1.4
| | | `-- pako@0.2.9
| | +-- buffer@4.9.1
| | | +-- base64-js@1.2.0
| | | `-- ieee754@1.1.8
| | +-- console-browserify@1.1.0
| | | `-- date-now@0.1.4
| | +-- constants-browserify@1.0.0
| | +-- crypto-browserify@3.3.0
| | | +-- browserify-aes@0.4.0
| | | +-- pbkdf2-compat@2.0.1
| | | +-- ripemd160@0.2.0
| | | `-- sha.js@2.2.6
| | +-- domain-browser@1.1.7
| | +-- events@1.1.1
| | +-- https-browserify@0.0.1
| | +-- os-browserify@0.2.1
| | +-- path-browserify@0.0.0
| | +-- process@0.11.9
| | +-- punycode@1.4.1
| | +-- querystring-es3@0.2.1
| | +-- stream-browserify@2.0.1
| | +-- stream-http@2.5.0
| | | +-- builtin-status-codes@2.0.0
| | | +-- readable-stream@2.2.2
| | | | `-- buffer-shims@1.0.0
| | | +-- to-arraybuffer@1.0.1
| | | `-- xtend@4.0.1
| | +-- string_decoder@0.10.31
| | +-- timers-browserify@2.0.2
| | | `-- setimmediate@1.0.5
| | +-- tty-browserify@0.0.0
| | +-- url@0.11.0
| | | +-- punycode@1.3.2
| | | `-- querystring@0.2.0
| | +-- util@0.10.3
| | | `-- inherits@2.0.1
| | `-- vm-browserify@0.0.4
| |   `-- indexof@0.0.1
| +-- optimist@0.6.1
| | `-- wordwrap@0.0.2
| +-- supports-color@3.1.2
| | `-- has-flag@1.0.0
| +-- tapable@0.1.10
| +-- uglify-js@2.7.5
| | +-- async@0.2.10
| | +-- uglify-to-browserify@1.0.2
| | `-- yargs@3.10.0
| |   +-- camelcase@1.2.1
| |   +-- cliui@2.1.0
| |   | +-- center-align@0.1.3
| |   | | +-- align-text@0.1.4
| |   | | | +-- longest@1.0.1
| |   | | | `-- repeat-string@1.6.1
| |   | | `-- lazy-cache@1.0.4
| |   | `-- right-align@0.1.3
| |   `-- window-size@0.1.0
| +-- watchpack@0.2.9
| | +-- async@0.9.2
| | `-- chokidar@1.6.1
| |   +-- anymatch@1.3.0
| |   | `-- arrify@1.0.1
| |   +-- async-each@1.0.1
| |   +-- glob-parent@2.0.0
| |   | `-- is-glob@2.0.1
| |   |   `-- is-extglob@1.0.0
| |   +-- is-binary-path@1.0.1
| |   | `-- binary-extensions@1.8.0
| |   +-- is-glob@2.0.1
| |   | `-- is-extglob@1.0.0
| |   `-- readdirp@2.1.0
| |     `-- set-immediate-shim@1.0.1
| `-- webpack-core@0.6.9
|   `-- source-map@0.4.4
|     `-- amdefine@1.0.1
+-- webpack-dev-server@1.16.2
| +-- compression@1.6.2
| | +-- accepts@1.3.3
| | | `-- negotiator@0.6.1
| | +-- bytes@2.3.0
| | +-- compressible@2.0.9
| | +-- debug@2.2.0
| | | `-- ms@0.7.1
| | +-- on-headers@1.0.1
| | `-- vary@1.1.0
| +-- connect-history-api-fallback@1.3.0
| +-- express@4.14.0
| | +-- array-flatten@1.1.1
| | +-- content-disposition@0.5.1
| | +-- content-type@1.0.2
| | +-- cookie@0.3.1
| | +-- cookie-signature@1.0.6
| | +-- debug@2.2.0
| | | `-- ms@0.7.1
| | +-- depd@1.1.0
| | +-- encodeurl@1.0.1
| | +-- escape-html@1.0.3
| | +-- etag@1.7.0
| | +-- finalhandler@0.5.0
| | | +-- debug@2.2.0
| | | | `-- ms@0.7.1
| | | +-- statuses@1.3.1
| | | `-- unpipe@1.0.0
| | +-- fresh@0.3.0
| | +-- merge-descriptors@1.0.1
| | +-- methods@1.1.2
| | +-- on-finished@2.3.0
| | | `-- ee-first@1.1.1
| | +-- parseurl@1.3.1
| | +-- path-to-regexp@0.1.7
| | +-- proxy-addr@1.1.2
| | | +-- forwarded@0.1.0
| | | `-- ipaddr.js@1.1.1
| | +-- qs@6.2.0
| | +-- range-parser@1.2.0
| | +-- send@0.14.1
| | | +-- debug@2.2.0
| | | +-- destroy@1.0.4
| | | +-- mime@1.3.4
| | | `-- ms@0.7.1
| | +-- serve-static@1.11.1
| | +-- type-is@1.6.14
| | | `-- media-typer@0.3.0
| | `-- utils-merge@1.0.0
| +-- http-proxy-middleware@0.17.2
| | +-- http-proxy@1.16.2
| | | +-- eventemitter3@1.2.0
| | | `-- requires-port@1.0.0
| | `-- micromatch@2.3.11
| |   +-- arr-diff@2.0.0
| |   | `-- arr-flatten@1.0.1
| |   +-- array-unique@0.2.1
| |   +-- braces@1.8.5
| |   | +-- expand-range@1.8.2
| |   | | `-- fill-range@2.2.3
| |   | |   +-- is-number@2.1.0
| |   | |   +-- isobject@2.1.0
| |   | |   `-- randomatic@1.1.6
| |   | +-- preserve@0.2.0
| |   | `-- repeat-element@1.1.2
| |   +-- expand-brackets@0.1.5
| |   | `-- is-posix-bracket@0.1.1
| |   +-- extglob@0.3.2
| |   | `-- is-extglob@1.0.0
| |   +-- filename-regex@2.0.0
| |   +-- is-extglob@1.0.0
| |   +-- is-glob@2.0.1
| |   +-- kind-of@3.1.0
| |   | `-- is-buffer@1.1.4
| |   +-- normalize-path@2.0.1
| |   +-- object.omit@2.0.1
| |   | +-- for-own@0.1.4
| |   | | `-- for-in@0.1.6
| |   | `-- is-extendable@0.1.1
| |   +-- parse-glob@3.0.4
| |   | +-- glob-base@0.3.0
| |   | | `-- is-glob@2.0.1
| |   | |   `-- is-extglob@1.0.0
| |   | +-- is-dotfile@1.0.2
| |   | +-- is-extglob@1.0.0
| |   | `-- is-glob@2.0.1
| |   `-- regex-cache@0.4.3
| |     +-- is-equal-shallow@0.1.3
| |     `-- is-primitive@2.0.0
| +-- open@0.0.5
| +-- serve-index@1.8.0
| | +-- batch@0.5.3
| | +-- debug@2.2.0
| | | `-- ms@0.7.1
| | `-- http-errors@1.5.1
| |   `-- setprototypeof@1.0.2
| +-- sockjs@0.3.18
| | +-- faye-websocket@0.10.0
| | | `-- websocket-driver@0.6.5
| | |   `-- websocket-extensions@0.1.1
| | `-- uuid@2.0.3
| +-- sockjs-client@1.1.1
| | +-- debug@2.3.3
| | | `-- ms@0.7.2
| | +-- eventsource@0.1.6
| | | `-- original@1.0.0
| | |   `-- url-parse@1.0.5
| | +-- faye-websocket@0.11.0
| | +-- json3@3.3.2
| | `-- url-parse@1.1.7
| |   `-- querystringify@0.0.4
| +-- stream-cache@0.0.2
| +-- strip-ansi@3.0.1
| | `-- ansi-regex@2.0.0
| `-- webpack-dev-middleware@1.8.4
|   `-- mime@1.3.4
`-- webpack-merge@0.16.0
  +-- lodash.find@3.2.1
  | +-- lodash._basecallback@3.3.1
  | | +-- lodash._baseisequal@3.0.7
  | | +-- lodash._bindcallback@3.0.1
  | | `-- lodash.pairs@3.0.1
  | +-- lodash._baseeach@3.0.4
  | +-- lodash._basefind@3.0.0
  | +-- lodash._basefindindex@3.6.0
  | +-- lodash.isarray@3.0.4
  | `-- lodash.keys@3.1.2
  +-- lodash.isequal@4.4.0
  +-- lodash.isplainobject@3.2.0
  | +-- lodash._basefor@3.0.3
  | +-- lodash.isarguments@3.1.0
  | `-- lodash.keysin@3.0.8
  `-- lodash.merge@3.3.2
    +-- lodash._arraycopy@3.0.0
    +-- lodash._arrayeach@3.0.0
    +-- lodash._createassigner@3.1.1
    | +-- lodash._isiterateecall@3.0.9
    | `-- lodash.restparam@3.6.1
    +-- lodash._getnative@3.9.1
    +-- lodash.istypedarray@3.0.6
    `-- lodash.toplainobject@3.0.0
      `-- lodash._basecopy@3.0.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
(node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.0.15: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
