### ISSUE TITLE
Runtime error: Cannot read property 'appendChild' of null(…)

### ISSUE THREAD

**Issue by kittykatattack** [moarwick/elm-webpack-starter#42]
I have some code that compiles and runs fine in elm reactor.
However, when I run code the code with elm-webpack-starter I'm getting this runtime error:

```
Cannot read property 'appendChild' of null
```

The problem code is `parentNode.appendChild(appNode);` from this block of ode in `main.js`

	function debugRenderer(moduleName, parentNode, popoutRef, view, viewIn, viewOut)
	{
		return function(tagger, initialModel)
		{
			var appEventNode = { tagger: tagger, parent: undefined };
			var eventNode = { tagger: tagger, parent: undefined };

			// make normal stepper
			var appVirtualNode = view(initialModel);
			var appNode = render(appVirtualNode, appEventNode);
			parentNode.appendChild(appNode);
			var appStepper = makeStepper(appNode, view, appVirtualNode, appEventNode);

			// make overlay stepper
			var overVirtualNode = viewIn(initialModel)._1;
			var overNode = render(overVirtualNode, eventNode);
			parentNode.appendChild(overNode);
			var wrappedViewIn = wrapViewIn(appEventNode, overNode, viewIn);
			var overStepper = makeStepper(overNode, wrappedViewIn, overVirtualNode, eventNode);

			// make debugger stepper
			var debugStepper = makeDebugStepper(initialModel, viewOut, eventNode, parentNode, moduleName, popoutRef);

			return function stepper(model)
			{
				appStepper(model);
				overStepper(model);
				debugStepper(model);
			}
		};
	}

It looks like `tagger` has an undefined parent. 
Does anyone know what the problem might be?

**Comment by moarwick** [comment]
assuming no longer an issue? i'd reclone and reinstall latest, make sure you are on Node 6+

**Comment by JordyMoos** [comment]
I have the same issue "Uncaught TypeError: Cannot read property 'appendChild' of null at bundle.js:17580"

Using node v8.9.1

**Comment by JordyMoos** [comment]
Oke my error was that i did not add html to my index.ejs file. After adding the plain html there it worked again. Maybe usefull for the next person with this error
