### ISSUE TITLE
Hot reloading on save does not work for imported components

### ISSUE THREAD

**Issue by madnight** [moarwick/elm-webpack-starter#44]
It seems like hot auto reloading on save does not work for imported components.
So in this case it does not work for Hello.elm, but Main.elm hot reloading on save works fine.

**Comment by kldeb** [comment]
@madnight If you search through the issues this was supposed to be fixed a while ago. I had the same problem. 

I added the following line to the top of Main.elm:

```module Main exposing (..)```

That fixed my problem. 

https://github.com/rtfeldman/node-elm-compiler/pull/36#issuecomment-239791195

**Comment by moarwick** [comment]
Updated in 0.8.4
