### ISSUE TITLE
WIndows not working, FIXED

### ISSUE THREAD

**Issue by madasebrof** [moarwick/elm-webpack-starter#46]
FYI, running Windows 10.

To get this to run on windows, I had to make the following changes to webpack.config.js:

```javascript
  output: {
    path:       outputPath,
    // filename:   path.join( 'static/js/', outputFilename ),
    filename:   "bundle.js",
    publicPath: '/'
  },
```

Other than that, nice starting place!

(also looks like bootstrap icon fonts aren't being bundled in the production build for some reason...)

**Comment by moarwick** [comment]
please try the latest version. the local server/bundler should work fine.

unfortunately, `npm run build` is not Windows-compatible at the moment. see comments in this [PR](https://github.com/moarwick/elm-webpack-starter/pull/39). for now, you can just remove all the `mv` commands from the script, then copy the font files into `dist/static/css` manually..
