### ISSUE TITLE
Upgrade to Webpack 2

### ISSUE THREAD

**Issue by optikfluffel** [moarwick/elm-webpack-starter#52]
We should probably [migrate to webpack 2](https://webpack.js.org/guides/migrating/) and update all other dependencies along the way too. I could give it a shot during the following week if that's ok with everyone. Any thoughts on that?

**Comment by eeue56** [comment]
Porting the loader is the tricky part - this repo is mainly just boilerplate around that. A PR has already been made for the changes for webpack v2 on the loader, https://github.com/elm-community/elm-webpack-loader/pull/105

I would love some help reviewing stuff there, if you already familiar with that migration.

**Comment by jiwhiz** [comment]
@optikfluffel Please review my PR #53 and let me know if you find any issues.

**Comment by jiwhiz** [comment]
Sorry @optikfluffel, forgot to watch this repo, so didn't see your review. I updated code based on your feedback. Thanks a lot!.

BTW, I create a new starter project at https://github.com/jiwhiz/elm-bootstrap-webpack-starter, with [elm-bootstrap](https://github.com/rundis/elm-bootstrap) support, and made [elm-css-webpack-loader](https://github.com/tcoopman/elm-css-webpack-loader/pull/12) working. Hope you guys give me some feedback. Not a frontend developer, but love Elm so much!

**Comment by mcmire** [comment]
Just rooting around this repo and noticed the changes that have been made recently. With 4a2d21ce4b8950c39e23e4b9a4a9d4d26cc9ee4f done, can this be closed?
