### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by davejacobs** [moarwick/elm-webpack-starter#64]
I'm trying out elm-webpack-starter, and it's made getting started really easy. However, I'm not able to see any bootstrap styles besides Glyphicons in my generated index.html with the default config (using `npm start`). Is there an extra step I'm missing?

**Comment by davejacobs** [comment]
Nevermind, I made a silly mistake.

**Comment by eeue56** [comment]
@davejacobs You should share what your mistake was so that anyone who finds this in the future can see how you fixed it :)
