### ISSUE TITLE
Include elm-hot-loader

### ISSUE THREAD

**Issue by gothy** [moarwick/elm-webpack-starter#8]
Hi Peter,

it would be really great to include [elm-hot-loader](https://github.com/fluxxu/elm-hot-loader) into the starter kit. I've just spent about an hour tying all the things together. I could make a PR, but I'm not that profound in Elm so far and all the nuances of StartApp(example in elm-hot-loader repo) vs StartApp.Simple.

Thanks for your work!

**Comment by moarwick** [comment]
@gothy: Done. Your friend @fluxxu was kind enough to do the PR. :)
